config/routes.rb
ElevenAMcafe::Application.routes.draw do

match 'matches/new', :action =>'new', :controller => 'matches', :as=>'new', :via =>'POST'
match 'matches/show', :action =>'show', :controller =>'matches', :as=>'show', :via => 'GET'
match 'matches', :action => 'delete_match', :controller =>'matches', :as=>'delete_match', :via => 'DELETE'
match '11amcafe', :action => 'index', :controller =>'elevenAmCafe', :as => 'welcome', :via => 'GET'
match '11amcafe/customer_support', :action => 'customer_support', :controller =>'elevenAmCafe', :as => 'customer_support', :via => 'GET'
match '11amcafe/forget_password', :action => 'forget_password', :controller =>'elevenAmCafe', :as => 'forget_password', :via => 'GET'
match '11amcafe/send_forgotten_password', :action => 'send_forgotten_password', :controller =>'elevenAmCafe', :as => 'send_forgotten_password', :via => 'POST'
match '11amcafe/sweep_old_sessions', :action => 'sweep_old_sessions', :controller =>'elevenAmCafe', :via => 'GET'
match '11amcafe/get_picture/:name', :action => 'get_picture_ss', :controller => 'elevenAmCafe', :as => 'get_picture_ss', :via => 'GET'
match '11amcafe/add_picture', :action => 'add_picture_ss', :controller => 'elevenAmCafe', :as => 'add_picture_ss', :via => 'POST'
match '11amcafe/delete_picture', :action => 'delete_picture_ss', :controller => 'elevenAmCafe', :as => 'delete_picture_ss', :via => 'GET'
match '11amcafe/save_user_information', :action => 'save_user_information_ss', :controller => 'elevenAmCafe', :as => 'save_user_information_ss', :via => 'POST'

match '11amcafe/company', :action => 'company', :controller => 'help', :as => 'company', :via => 'GET'
match '11amcafe/privacy', :action => 'privacy', :controller => 'help', :as => 'privacy', :via => 'GET'
match '11amcafe/policy', :action => 'policy', :controller => 'help', :as => 'policy', :via => 'GET'
match '11amcafe/help', :action => 'help', :controller => 'help', :as => 'help', :via => 'GET'

match 'users', :action => 'index', :controller => 'usersAmCafe', :as => 'users', :via => 'GET'
match 'users', :action => 'create', :controller => 'usersAmCafe', :via => 'POST'
match 'users/new', :action => 'new', :controller => 'usersAmCafe', :as => 'new_user', :via => 'GET'
match 'users', :action => 'destroy', :controller => 'usersAmCafe', :as => 'delete', :via => 'DELETE'
match 'users/sign_in', :action => 'sign_in', :controller => 'usersAmCafe', :as => 'sign_in', :via => 'POST'
match 'users/second_step_new_user', :action => 'second_step_new_user', :controller => 'usersAmCafe', :as => 'second_step_new_user', :via => 'GET'

match 'members', :action => 'index', :controller => 'membersAmCafe', :as => 'members', :via => 'GET'
match 'members/add_picture', :action => 'add_picture', :controller => 'membersAmCafe', :as => 'add_picture', :via => 'POST'
match 'members/get_picture/:name', :action => 'get_picture', :controller => 'membersAmCafe', :as => 'get_picture', :via => 'GET'
match 'members/delete_picture', :action => 'delete_picture', :controller => 'membersAmCafe', :as => 'delete_picture', :via => 'GET'
match 'members/validation', :action => 'validation', :controller => 'membersAmCafe', :as => 'validation', :via => 'GET'
match 'members/validate_sms', :action => 'validate_sms', :controller => 'membersAmCafe', :as => 'validate_sms', :via => 'GET'
match 'members/validate_email', :action => 'validate_email', :controller => 'membersAmCafe', :as => 'validate_email', :via => 'GET'
match 'members/validate_email_web', :action => 'validate_email_web', :controller => 'membersAmCafe', :as => 'validate_email_web', :via => 'GET'
match 'members/edit_profile', :action => 'edit_profile', :controller => 'membersAmCafe', :as => 'edit_profile', :via => 'GET'
match 'members/add_user_information', :action => 'add_user_information', :controller => 'membersAmCafe', :as => 'add_user_information', :via => 'GET'
match 'members/save_basic_info', :action => 'save_basic_info', :controller => 'membersAmCafe', :as => 'save_basic_info', :via => 'POST'
match 'members/save_new_phone', :action => 'save_new_phone', :controller =>'membersAmCafe', :as => 'save_new_phone', :via => 'POST'
match 'members/save_new_password', :action => 'save_new_password', :controller =>'membersAmCafe', :as => 'save_new_password', :via => 'POST'
match 'members/save_user_information', :action => 'save_user_information', :controller => 'membersAmCafe', :as => 'save_user_information', :via => 'POST'
match 'members/send_sms_validation', :action => 'send_sms_validation', :controller => 'membersAmCafe', :as => 'send_sms_validation', :via => 'GET'
match 'members/send_email_validation', :action => 'send_email_validation', :controller => 'membersAmCafe', :as => 'send_email_validation', :via => 'GET'
match 'members/logout', :action => 'logout', :controller => 'membersAmCafe', :as => 'logout', :via => 'GET'
match 'members/save_password', :action => 'save_password', :controller =>'membersAmCafe', :as => 'save_password', :via => 'POST'
match 'members/new_password', :action => 'new_password', :controller =>'membersAmCafe', :as => 'new_password', :via => 'GET'
match 'members/show_matches', :action => 'show_matches', :controller =>'membersAmCafe', :as => 'show_matches', :via => 'GET'
match 'members/not_activated', :action => 'not_activated', :controller =>'membersAmCafe', :as => 'not_activated', :via => 'GET'
match 'members/get_picture_match/:name', :action => 'get_picture_match', :controller =>'membersAmCafe', :as => 'get_picture_match', :via => 'GET'
match 'members/choose_match', :action => 'choose_match', :controller => 'membersAmCafe', :as => 'choose_match', :via => 'GET'
match 'members/like_match', :action => 'like_match', :controller => 'membersAmCafe', :as => 'like_match', :via => 'POST'
match 'members/customer_support', :action => 'customer_support', :controller =>'membersAmCafe', :as => 'member_customer_support', :via => 'GET'
match 'members/customer_support_finish', :action => 'customer_support_finish', :controller =>'membersAmCafe', :as => 'customer_support_finish', :via => 'GET'
match 'members/get_match_phone', :action => 'get_match_phone', :controller => 'membersAmCafe', :as => 'get_match_phone', :via => 'POST'
match 'members/save_rating', :action => 'save_rating', :controller => 'membersAmCafe', :as => 'save_rating', :via => 'POST'
match 'members/company_l', :action => 'company_l', :controller => 'membersAmCafe', :as => 'company_l', :via => 'GET'
match 'members/privacy_l', :action => 'privacy_l', :controller => 'membersAmCafe', :as => 'privacy_l', :via => 'GET'
match 'members/policy_l', :action => 'policy_l', :controller => 'membersAmCafe', :as => 'policy_l', :via => 'GET'
match 'members/help_l', :action => 'help_l', :controller => 'membersAmCafe', :as => 'help_l', :via => 'GET'
match 'members/delete_account', :action => 'delete_account', :controller => 'membersAmCafe', :as => 'delete_account', :via => 'GET'
match 'members/delete_final', :action => 'delete_final', :controller => 'membersAmCafe', :as => 'delete_final', :via => 'POST'
match 'members/suspend_final', :action => 'suspend_final', :controller => 'membersAmCafe', :as => 'suspend_final', :via => 'POST'

match 'admin/admin_profile', :action => 'admin_profile', :controller => 'adminAmCafe', :as =>'admin_profile', :via => 'GET'
match 'admin/save_admin_new_password', :action => 'save_admin_new_password', :controller => 'adminAmCafe', :as => 'save_admin_new_password', :via => 'POST'
match 'admin/show_invalid_male_users', :action => 'show_invalid_male_users', :controller => 'adminAmCafe', :as => 'show_invalid_male_users', :via => 'GET'
match 'admin/show_invalid_female_users', :action => 'show_invalid_female_users', :controller => 'adminAmCafe', :as => 'show_invalid_female_users', :via => 'GET'
match 'admin/validate_user', :action => 'validate_user', :controller => 'adminAmCafe', :as => 'validate_user', :via => 'POST'
match 'admin/reject_user', :action => 'reject_user', :controller => 'adminAmCafe', :as => 'reject_user', :via => 'POST'
match 'admin/get_user_picture/:name', :action => 'get_user_picture', :controller => 'adminAmCafe', :as => 'get_user_picture', :via => 'GET'

end

app/controllers/users_am_cafe_controller.rb
class Hash
  def add(key, msg)
    self.merge(key => msg)
  end
end

class UsersAmCafeController < ApplicationController
  include ReCaptcha::AppHelper
  
  
  def show
    response = UsersAmCafe.getUser(params["email"])
	if response[:status].eql?("OK")
	  @user = response[:user]
	else
	  @users = response[:user]
	  @error = response[:errors]
	  redirect_to users_path
	end
  end
  
  def index
    users_db = UsersAmCafe.all
    @users = []
    users_db.each do |user|
      @users << user.attributes.to_h
    end
    @users
  end
  
  def new
    
  end
  
  def create
    error = {}
    @usr = {}
    #join birthdate
    if params[:user] && params[:user]["birthdate(1i)"]
      birthdate = params[:user]["birthdate(1i)"].to_s + '-' + params[:user]["birthdate(2i)"].to_s.rjust(2,'0') + '-' + params[:user]["birthdate(3i)"].to_s.rjust(2,'0')
      params[:user].delete("birthdate(1i)")
      params[:user].delete("birthdate(2i)")
      params[:user].delete("birthdate(3i)")
      params[:user]["birthdate"]=birthdate
    end
    
    #if params[:user] && params[:user]["city"]
      #if params[:user]["city"].include?("All")
      #  params[:user]["city_en"]=["All"]
      #else
      #  value = params[:user]["city"]
      #  if value.instance_of?(String)
      #    value = [] << value 
      #  else #if value.instance_of(Set)
      #    value = value.to_a
      #  end
      #  params[:user]["city_en"] = []
      #  value.each do |city|
      #  id = City.find_by_name_and_locale(city, I18n.locale.to_s.upcase)
      #    if id
      #      id = id.id
      #      params[:user]["city_en"] << City.find_by_id_and_locale(id, "EN").name
      #    end
      #  end
      #end
    #end
    
    #if validate_recap(params, error, {:msg => I18n.t(:recaptcha_failed)})
	    email = params[:user]["email"]
	    password = params[:user]["password"]
  	  response = UsersAmCafe.createUser(params[:user])
	    if response and response[:status].eql?('OK')
		      MembersAmCafe.send_email_validation({:email => email, :password => password})
          flash[:notice] = I18n.t(:registration_correct)
          render :signup_finish#second_step_new_user_path({:email => params[:user]["email"], :from_search => params["from_search"]})
      else
  		  flash[:error] = (I18n.t(:registration_error) + ". <br>" + response[:errors].join("<br>")).html_safe
  		  @usr = params[:user]
  		  render :action => 'new'
      end
    #else
    #  flash[:error] = I18n.t(:recaptcha_failed)
    #  @usr = params[:user]
	  #  render :action => 'new'
    #end
	
  end
  
  def second_step_new_user
    #if (params["from_search"].eql?("new") || params["from_search"].eql?("second_step_new_user")) && !params[:email].nil?
    if refered_from_our_site? && refered_from_user_signup?
      session[:email]=params[:email]
      @member ||= UsersAmCafe.getUser(session[:email])[:user]
      if !@member || !@member["email"]
        redirect_to welcome_path
      end
    else 
      redirect_to welcome_path
    end
  end
  
  def update
    UsersAmCafe.updateUser(params[:user])
    flash[:notice] = I18n.t(:user_update_correct)
    redirect_to users_path
  end
  
  def http_referer_uri
    request.env["HTTP_REFERER"] && URI.parse(request.env["HTTP_REFERER"])
  end

  def refered_from_our_site?
    if uri = http_referer_uri
      uri.host == request.host
    end
  end

  def refered_from_user_signup?
    if refered_from_our_site?
      http_referer_uri.try(:path)['users/new'] || http_referer_uri.try(:path)['users/second_step_new_user'] || http_referer_uri.try(:path)['users/delete_picture_ss']
    end
  end
  
  def edit
    @user = UsersAmCafe.getUser(params["email"])
  end
  
  def destroy
    if UsersAmCafe.deleteUser(params["email"])
      flash[:error]=I18n.t(:user_pictures_delete_error) unless PicturesAmCafe.removeAllPictures(params["email"])
      flash[:notice] = I18n.t(:user_delete_correct) unless flash[:error]
      matches = Match.where("email = ? or match_email= ?", params["email"], params["email"])
      matches.each do |match|
        match.destroy
      end if matches
      @ses = Session.find_by_email(params["email"])
      @ses.destroy if @ses
    else
      flash[:error] = I18n.t(:user_delete_error)
    end
    redirect_to welcome_path
  end
  
  def show
    response = UsersAmCafe.getUser(params["email"])
    @user = response[:user]
    flash[:error]=response[:errors]
  end
  
  def sign_in
    response=UsersAmCafe.sign_in(params["email"],params["password"])
    @user = response[:user]
    flash[:error]=response[:errors].join("<br>")
    if @user && @user.size>0
      # store auth token and email in session
      @ses = Session.new
      @ses.email = params["email"]
      @ses.session_id = params["authenticity_token"]
      if !@ses.save
        flash[:error]=I18n.t(:login_error)
        redirect_to welcome_path({:email => params["email"]})
      else
        cookies.permanent["authenticity_token"] = params["authenticity_token"]
        # redirect to members
        if UsersAmCafe.isAdmin?(params["email"])
          redirect_to admin_profile_path
        else
          redirect_to members_path
        end 
      end
    else
      redirect_to welcome_path({:email => params["email"]})
    end
  end
  
end

app/views/users_am_cafe/create.html.erb
<%if flash[:notice]%>
<div class="alert alert-success">
<button class="close" data-dismiss="alert">×</button><%=flash[:notice]%>
</div>
<%end%>
<%if flash[:error]%>
<div class="alert alert-error"><button class="close" data-dismiss="alert">×</button>
<%=flash[:error]%>
</div>
<%end%>

<input type='hidden' id='user_id' value='<%=@user[:id]%>'></input>

app/views/users_am_cafe/index.html.erb
<h1>List of Users</h1>
<%if flash[:notice]%>
<div class="alert alert-success">
<button class="close" data-dismiss="alert">×</button><%=flash[:notice]%>
</div>
<%end%>
<%if flash[:error]%>
<div class="alert alert-error"><button class="close" data-dismiss="alert">×</button>
<%=flash[:error]%>
</div>
<%end%>
<table cellpadding="10px">
	<thead>
		<th>Name</th>
		<th>Email</th>
		<th>Birthdate</th>
		<th>BloodType</th>
		<th>Phone Number</th>
		<th>Gender</th>
		<th>Age Preference</th>
		<th></th>
	</thead>
	<tbody>
<%@users.each do |user|%>
<tr><td><%=user["name"]%></td><td><%=user["email"]%></td><td><%=user["birthdate"]%></td><td><%=user["bloodType"]%></td><td><%=user["phone"]%></td><td><%=user["gender"]%></td><td><%=user["age_preference"]%></td>
	<td>
	<%=form_tag delete_path, :method=>:delete do%>
	<%=hidden_field_tag "email", user["email"]%>
	<%=submit_tag "Delete"%>
	<%end%>
</tr>
<%end%>
<a href='/users/new' id='Register'>Register</a>
</form> 
</tbody>




</table>

app/views/users_am_cafe/second_step_new_user.html.erb
<div style="display:none" id="Time"></div>
<div class="row" style="padding-top:15px;">
<div id="main">
	<div id="content">
      	<%if flash[:notice]%>
		<div class="alert alert-success" style="padding-top:15px">
		<a class="close" href="#" data-dismiss="alert">&times;</a>
		<%=flash[:notice]%>
		</div>
		<%end%>
		<%if flash[:error]%>
		<div class="alert alert-error" style="padding-top:15px">
			<a class="close" href="#" data-dismiss="alert">&times;</a>
		<%=flash[:error]%>
		</div>
		<%end%>
     <h2 class="title">あなたはどんな人？</h2>
   <table class="process_bar" cellpadding="1" cellspacing="0" border="0">
    		<tbody><tr>
				<td class="process">基本情報入力</td>
              	<td class="process_img"></td>
				<td class="process">メールアドレス認証</td>
                <td class="process_img_2"></td>
				<td class="process_keyword onPage">キーワード入力と写真設定</td>
         		<td class="process_img_onPage"></td>
				<td class="process">プロフィール認証</td>
			
                
            </tr></tbody>
</table>
			<div class="alert alert-error">
	        注意：キーワードと写真が入力されていないと、プロフィール認証されず、カードがやってきません！
	        </div>
				<%=form_tag save_user_information_ss_path, :method => :post do%>			
				<%=hidden_field_tag "email", @member["email"]%>
				<%=MemberHelper.advance_profile_tag :advance, nil, nil, @member, ["	優しい、完璧主義者、肉食系、草食系、
					夢追い人、結構いい加減、怠け者、お調子者、働き者、情熱的、気分屋、明るい、真面目、社交的、器用、
					ウソがつけない、天然とよく言われる、寂しがり屋、人なつこい、バカ正直、落ち着いている、引っ込み思案、ストイックな性格、
					細マッチョ、長女、末っ子、楽観的、甘えん坊、身長180cm、運動好き、スリム、努力家、家庭的、不器用", "優しい人、面白い人、嘘つかない人、昼寝、新しいもの、サッカー、ショッピング、お菓子作り、飲み会、
					慣れ親しんだもの、 スイーツ、秋、イケメン、ドライブ、温泉、マッサージ、旅行、おしゃべり、ペット、筋トレ、ジョギング、自己啓発、
					テレビ、ゴルフ、健康グッズ、人助け、お笑い、ネットサーフィン 、ボーっとすること、重ね着、すっぴん、ぼっちゃり、スリム、流行りモノ", "満員電車、人ごみ、タバコ、女みたいな男、がさつな女、怖い話、野菜、空気が読めない人、
気を遣いすぎる人、お酒、化粧、高所、努力しない人、ケチな人、冷めたご飯、きつい香水、暑さ、噂話、日曜のサザエさん、潔癖な私、
ストレスで食に走る私、気性が荒い人、自慢する人、人の話を聞かない人、失礼な人、不潔な人、格好悪い人、怖い人、うそつき、浮気性、遊び人、怠け者", "愛車、マイホーム、自転車、
コーヒーメーカー、50インチテレビ、沢山のゲーム、長身、つぶらな瞳、英検1級、
長い指、野菜ソムリエ資格、豊かな髪、美肌、輝く笑顔、白い歯、健康な体、運転免許、ペット、ユーモア、筋の通ったきれいな鼻、美しい手、歌唱力、
美的センス、漢字検定3級、剣道初段、書道師範、ダイビング免許、大家族、信頼できる友人、流行の服、iPhone、一眼カメラ", "長期休暇、昇給、私を大切にしてくれる恋人、愉快な同僚、なんでも話せる異性の友人、
未来を見通す目、透き通るような白い肌、元気な髪の毛、とにかくお金、豪邸、画力、センス、行動力、度胸、
謙虚さ、知恵、忍耐力、時間、大型バイク、夢、高級車、ホームシアター、一緒に頑張れる仲間、頼れる上司、信頼できる部下、
人気、愛情、世界一周旅行、自由、焼肉食べ放題、親友", "ノルウェイの森、星の王子さま、アルケミスト、七つの習慣、人を動かす、シークレット、
ダ・ヴィンチ・コード、老人と海、ハムレット、三国志、西遊記、竜馬がゆく、シャーロックホームズ、坂の上の雲、沈まぬ太陽、
白夜行、進撃の巨人、岳、SEVEN SEEDS、3月のライオン、ワンピース、花より男子、犬夜叉、宇宙兄弟、スラムダンク、僕等がいた、ドラゴンボール、HUNTER×HUNTER", "ビートルズ、Green day、ベートーベン交響曲第9番、マイケル・ジャクソン、ミスチル、いきものがかり、EXILE、
嵐、JUJU、AKB48、東方神起、福山雅治、レディー・ガガ、少女時代、KARA、リンキン・パーク、君が代、ヘビーローテーション、栄光の架け橋へ、
シーソーゲーム、真夏の果実、My way、Dirty、恋のマイアヒ、Angel of The Light、葉加瀬太郎、風が吹いている", "パイレーツ・オプ・カリビアン、アバター、MI3、マトリックス、千と千尋の神隠し、ハリーポッター、
ラブ・アクチュアリー、王様と私、ゴッドファーザー、踊る大捜査線、猟奇的な彼女、タイタニック、トイ・ストーリー、ロード・オブ・ザ・リング、
スパイダーマン、スターウォーズ、バットマン、ハウルの動く城、風と共に去りぬ、サウンド・オブ・ミュージック、カンフーパンダ", "和食派、洋食派、中華派、多国籍派、外食派、自炊派、ごはん党、パン党、めん党、
濃厚とんこつラーメン、寿司、やきいも、チョコレート、天ぷら、鍋料理、グミ、うどん、ハード系もっちりパン、チーズケーキ、
梅干し、スナック菓子、ビール、味噌汁、スイカ、焼肉、ハンバーガー、冷麺、アイス、羊羹、マカロン、ワイン、グラタン、ピザ、トンカツ、ステーキ、炭酸飲料、トマト", "無償で与えるもの、永遠、すごく欲しい、生き甲斐、得がたいもの、喜び、幸福、平和、美しい、
わからない、情熱、穏やかな心、おもいやり、エロス、すべてを受け入れること、信頼、成長、自分を知ること、
ダイヤモンド、お金では買えない、語るものではない、砂漠の一砂、両親がお手本、努力なしでは得られない、最も根源的な欲望、無条件、自分を支える力、人生そのもの", "消防士、銀行員、IT、一般事務、営業、経営、SOHO、フリーター、
学生、留学生、教師、保母、シェフ、公務員、飲食店、弁護士、会計士、税理士、デザイナー、クリエイター、アパレル、
通訳、スポーツインストラクター、医師、看護師、楽しい、帰れない、しんどい、新入社員、課長、仕事が趣味、生き甲斐、3年目、
10社目、満足している、転職したい、男ばっかり、生きるため"]%>
				<%end%>
      
       
      	<%=form_tag add_picture_ss_path, :method=>:post, :remote => true, :multipart => true do%>
		<%=hidden_field_tag "email", @member["email"]%>
        <table class="photo_table" cellpadding="0" cellspacing="0" border="0">
        <tbody>
         <tr>
        <td colspan="3" class="title_table">
        <span class="large_text">STEP2.　あなたの写真をアップロードしましょう</span>
        <span class="small_text">※2つ以上の写真の登録が必須です</span></td></tr>
        <tr>
        <td class="td_photo"><div class="photo" id="essencial"><span class="photo_text"><%=link_to image_tag("/11amcafe/get_picture/1?type=t&token=" + ('a'..'z').to_a.shuffle[0,20].join.html_safe, :size=>"210x280"),"/11amcafe/get_picture/1", :target => "blank" %></span></div></td>
        <td class="td_photo"><div class="photo" id="essencial"><span class="photo_text"><%=link_to image_tag("/11amcafe/get_picture/2?type=t&token=" + ('a'..'z').to_a.shuffle[0,20].join.html_safe, :size=>"210x280"),"/11amcafe/get_picture/2", :target => "blank" %></span></div></td>
        <td class="td_photo"><div class="photo"><span class="photo_text"><%=link_to image_tag("/11amcafe/get_picture/3?type=t&token=" + ('a'..'z').to_a.shuffle[0,20].join.html_safe, :size=>"210x280"),"/11amcafe/get_picture/3", :target => "blank" %></span></div></td>
        
        </tr>
         <tr>
			<td class="td_button">
			<%=file_field_tag "pictures[1]",:accept => 'image/png,image/gif,image/jpeg,image/tiff', :style=>"width:120px"%>
			<%= link_to t(:delete_picture), delete_picture_ss_path("email"=> @member["email"],"name"=>'1'), :class=>"blue button"%>
			</td>
        	<td class="td_button">
			<%=file_field_tag "pictures[2]",:accept => 'image/png,image/gif,image/jpeg,image/tiff', :style=>"width:120px"%>
	        <%= link_to t(:delete_picture), delete_picture_ss_path("email"=> @member["email"],"name"=>'2'), :class=>"blue button"%>
			</td>
	        <td class="td_button">
			<%=file_field_tag "pictures[3]",:accept => 'image/png,image/gif,image/jpeg,image/tiff', :style=>"width:120px"%>
	        <%= link_to t(:delete_picture), delete_picture_ss_path("email"=> @member["email"],"name"=>'3'), :class=>"blue button"%>
			</td></tr>
          <tr>
        <td class="td_text">選択されていません</td>
        <td class="td_text">選択されていません</td>
        <td class="td_text">選択されていません</td>
        </tr>
        <tr>
        <td class="td_photo"><div class="photo"><span class="photo_text"><%=link_to image_tag("/11amcafe/get_picture/4?type=t&token=" + ('a'..'z').to_a.shuffle[0,20].join.html_safe, :size=>"210x280"),"/11amcafe/get_picture/4", :target => "blank" %></span></div></td>
        <td class="td_logo"><img src="/assets/11amcafe-logo-g.png"></td>
        <td class="td_photo"><div class="photo"><span class="photo_text"><%=link_to image_tag("/11amcafe/get_picture/5?type=t&token=" + ('a'..'z').to_a.shuffle[0,20].join.html_safe, :size=>"210x280"),"/11amcafe/get_picture/5", :target => "blank" %></span></div></td>
        </tr>
         <tr>
        	<td class="td_button">
			<%=file_field_tag "pictures[4]",:accept => 'image/png,image/gif,image/jpeg,image/tiff', :style=>"width:120px"%>
	        <%= link_to t(:delete_picture), delete_picture_ss_path("email"=> @member["email"],"name"=>'4'), :class=>"blue button"%>
			</td>
	        <td class="td_button"></td>
	        <td class="td_button">
			<%=file_field_tag "pictures[5]",:accept => 'image/png,image/gif,image/jpeg,image/tiff', :style=>"width:120px"%>
	        <%= link_to t(:delete_picture), delete_picture_ss_path("email"=> @member["email"],"name"=>'5'), :class=>"blue button"%>
			</td></tr>
         <tr>
        <td class="td_text">選択されていません</td>
        <td class="td_text"></td>
        <td class="td_text">選択されていません</td>
        </tr>
         <tr>
		<td colspan="3" class="warning_kw">
		注：必ず<strong>本人の顔が確認できる写真</strong>をアップロードしてください（各ファイル上限3MB）。団体写真など、本人以外の顔が写っている写真は利用できません。本人の写真でない場合、アカウントの登録を拒否、または停止、抹消されることがあります。</td>
		</tr>
         <tr>
		<td colspan="3">
		 <input class="orange button save" id="photo_save_button" name="submit" type="submit" value="保存して次へ">
		</td>
		</tr>
      
             </tbody>
        </table>  
     <%end%>
        
	</div>
	</div><div class="row" style="margin-top:0px;padding-top:0px;margin-left:5px;">
<div class="container" style="padding-top:0px;margin-top:0px;margin-bottom:0px;">

   
</div>
</div>
    
   

app/views/users_am_cafe/show.html.erb
<h2 align="center"><font color="red"><b><%if flash[:notice] %><%=flash[:notice]%><%else%><%=flash[:error]%><%end%></b></font><h2>

<input type='hidden' id='user_id' value='<%=@user[:id]%>'></input>