config/routes.rb
ElevenAMcafe::Application.routes.draw do

match 'matches/new', :action =>'new', :controller => 'matches', :as=>'new', :via =>'POST'
match 'matches/show', :action =>'show', :controller =>'matches', :as=>'show', :via => 'GET'
match 'matches', :action => 'delete_match', :controller =>'matches', :as=>'delete_match', :via => 'DELETE'
match '11amcafe', :action => 'index', :controller =>'elevenAmCafe', :as => 'welcome', :via => 'GET'
match '11amcafe/customer_support', :action => 'customer_support', :controller =>'elevenAmCafe', :as => 'customer_support', :via => 'GET'
match '11amcafe/forget_password', :action => 'forget_password', :controller =>'elevenAmCafe', :as => 'forget_password', :via => 'GET'
match '11amcafe/send_forgotten_password', :action => 'send_forgotten_password', :controller =>'elevenAmCafe', :as => 'send_forgotten_password', :via => 'POST'
match '11amcafe/sweep_old_sessions', :action => 'sweep_old_sessions', :controller =>'elevenAmCafe', :via => 'GET'
match '11amcafe/get_picture/:name', :action => 'get_picture_ss', :controller => 'elevenAmCafe', :as => 'get_picture_ss', :via => 'GET'
match '11amcafe/add_picture', :action => 'add_picture_ss', :controller => 'elevenAmCafe', :as => 'add_picture_ss', :via => 'POST'
match '11amcafe/delete_picture', :action => 'delete_picture_ss', :controller => 'elevenAmCafe', :as => 'delete_picture_ss', :via => 'GET'
match '11amcafe/save_user_information', :action => 'save_user_information_ss', :controller => 'elevenAmCafe', :as => 'save_user_information_ss', :via => 'POST'

match '11amcafe/company', :action => 'company', :controller => 'help', :as => 'company', :via => 'GET'
match '11amcafe/privacy', :action => 'privacy', :controller => 'help', :as => 'privacy', :via => 'GET'
match '11amcafe/policy', :action => 'policy', :controller => 'help', :as => 'policy', :via => 'GET'
match '11amcafe/help', :action => 'help', :controller => 'help', :as => 'help', :via => 'GET'

match 'users', :action => 'index', :controller => 'usersAmCafe', :as => 'users', :via => 'GET'
match 'users', :action => 'create', :controller => 'usersAmCafe', :via => 'POST'
match 'users/new', :action => 'new', :controller => 'usersAmCafe', :as => 'new_user', :via => 'GET'
match 'users', :action => 'destroy', :controller => 'usersAmCafe', :as => 'delete', :via => 'DELETE'
match 'users/sign_in', :action => 'sign_in', :controller => 'usersAmCafe', :as => 'sign_in', :via => 'POST'
match 'users/second_step_new_user', :action => 'second_step_new_user', :controller => 'usersAmCafe', :as => 'second_step_new_user', :via => 'GET'

match 'members', :action => 'index', :controller => 'membersAmCafe', :as => 'members', :via => 'GET'
match 'members/add_picture', :action => 'add_picture', :controller => 'membersAmCafe', :as => 'add_picture', :via => 'POST'
match 'members/get_picture/:name', :action => 'get_picture', :controller => 'membersAmCafe', :as => 'get_picture', :via => 'GET'
match 'members/delete_picture', :action => 'delete_picture', :controller => 'membersAmCafe', :as => 'delete_picture', :via => 'GET'
match 'members/validation', :action => 'validation', :controller => 'membersAmCafe', :as => 'validation', :via => 'GET'
match 'members/validate_sms', :action => 'validate_sms', :controller => 'membersAmCafe', :as => 'validate_sms', :via => 'GET'
match 'members/validate_email', :action => 'validate_email', :controller => 'membersAmCafe', :as => 'validate_email', :via => 'GET'
match 'members/validate_email_web', :action => 'validate_email_web', :controller => 'membersAmCafe', :as => 'validate_email_web', :via => 'GET'
match 'members/edit_profile', :action => 'edit_profile', :controller => 'membersAmCafe', :as => 'edit_profile', :via => 'GET'
match 'members/add_user_information', :action => 'add_user_information', :controller => 'membersAmCafe', :as => 'add_user_information', :via => 'GET'
match 'members/save_basic_info', :action => 'save_basic_info', :controller => 'membersAmCafe', :as => 'save_basic_info', :via => 'POST'
match 'members/save_new_phone', :action => 'save_new_phone', :controller =>'membersAmCafe', :as => 'save_new_phone', :via => 'POST'
match 'members/save_new_password', :action => 'save_new_password', :controller =>'membersAmCafe', :as => 'save_new_password', :via => 'POST'
match 'members/save_user_information', :action => 'save_user_information', :controller => 'membersAmCafe', :as => 'save_user_information', :via => 'POST'
match 'members/send_sms_validation', :action => 'send_sms_validation', :controller => 'membersAmCafe', :as => 'send_sms_validation', :via => 'GET'
match 'members/send_email_validation', :action => 'send_email_validation', :controller => 'membersAmCafe', :as => 'send_email_validation', :via => 'GET'
match 'members/logout', :action => 'logout', :controller => 'membersAmCafe', :as => 'logout', :via => 'GET'
match 'members/save_password', :action => 'save_password', :controller =>'membersAmCafe', :as => 'save_password', :via => 'POST'
match 'members/new_password', :action => 'new_password', :controller =>'membersAmCafe', :as => 'new_password', :via => 'GET'
match 'members/show_matches', :action => 'show_matches', :controller =>'membersAmCafe', :as => 'show_matches', :via => 'GET'
match 'members/not_activated', :action => 'not_activated', :controller =>'membersAmCafe', :as => 'not_activated', :via => 'GET'
match 'members/get_picture_match/:name', :action => 'get_picture_match', :controller =>'membersAmCafe', :as => 'get_picture_match', :via => 'GET'
match 'members/choose_match', :action => 'choose_match', :controller => 'membersAmCafe', :as => 'choose_match', :via => 'GET'
match 'members/like_match', :action => 'like_match', :controller => 'membersAmCafe', :as => 'like_match', :via => 'POST'
match 'members/customer_support', :action => 'customer_support', :controller =>'membersAmCafe', :as => 'member_customer_support', :via => 'GET'
match 'members/customer_support_finish', :action => 'customer_support_finish', :controller =>'membersAmCafe', :as => 'customer_support_finish', :via => 'GET'
match 'members/get_match_phone', :action => 'get_match_phone', :controller => 'membersAmCafe', :as => 'get_match_phone', :via => 'POST'
match 'members/save_rating', :action => 'save_rating', :controller => 'membersAmCafe', :as => 'save_rating', :via => 'POST'
match 'members/company_l', :action => 'company_l', :controller => 'membersAmCafe', :as => 'company_l', :via => 'GET'
match 'members/privacy_l', :action => 'privacy_l', :controller => 'membersAmCafe', :as => 'privacy_l', :via => 'GET'
match 'members/policy_l', :action => 'policy_l', :controller => 'membersAmCafe', :as => 'policy_l', :via => 'GET'
match 'members/help_l', :action => 'help_l', :controller => 'membersAmCafe', :as => 'help_l', :via => 'GET'
match 'members/delete_account', :action => 'delete_account', :controller => 'membersAmCafe', :as => 'delete_account', :via => 'GET'
match 'members/delete_final', :action => 'delete_final', :controller => 'membersAmCafe', :as => 'delete_final', :via => 'POST'
match 'members/suspend_final', :action => 'suspend_final', :controller => 'membersAmCafe', :as => 'suspend_final', :via => 'POST'

match 'admin/admin_profile', :action => 'admin_profile', :controller => 'adminAmCafe', :as =>'admin_profile', :via => 'GET'
match 'admin/save_admin_new_password', :action => 'save_admin_new_password', :controller => 'adminAmCafe', :as => 'save_admin_new_password', :via => 'POST'
match 'admin/show_invalid_male_users', :action => 'show_invalid_male_users', :controller => 'adminAmCafe', :as => 'show_invalid_male_users', :via => 'GET'
match 'admin/show_invalid_female_users', :action => 'show_invalid_female_users', :controller => 'adminAmCafe', :as => 'show_invalid_female_users', :via => 'GET'
match 'admin/validate_user', :action => 'validate_user', :controller => 'adminAmCafe', :as => 'validate_user', :via => 'POST'
match 'admin/reject_user', :action => 'reject_user', :controller => 'adminAmCafe', :as => 'reject_user', :via => 'POST'
match 'admin/get_user_picture/:name', :action => 'get_user_picture', :controller => 'adminAmCafe', :as => 'get_user_picture', :via => 'GET'

end

app/models/members_am_cafe.rb
class MembersAmCafe
  def self.validate_sms(params)
	YAML.load(User.post("validate_sms", params.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.validate_email(params)
    YAML.load(User.post("validate_email", params.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.send_sms_validation(params)
    YAML.load(User.post("send_sms_validation", params.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.send_email_validation(params)
    YAML.load(User.post("send_email_validation", params.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.validation_status(email)
    YAML.load(User.post("validation_status", {"email" => email}.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.new_password(email, code, password)
    YAML.load(User.post("reset_password", {"email" => email, "code" => code, "new_password" => password}.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.is_active(email)
	  auth_response = YAML.load(User.post("is_active", {"email" => email}.merge({"key"=>@@KEYLOGINCAFE})).body)
    return true unless auth_response.nil? || auth_response["message"].nil? || auth_response["message"].eql?("false") || !auth_response.instance_of?(Hash)
    false
  rescue StandardError => p
    false
  end
  
  def self.save_new_phone(email, password, new_phone)
    return nil if email.nil? || email.eql?("") || password.nil? || password.eql?("") || new_phone.nil? || new_phone.eql?("")
    YAML.load(User.post("reset_phone", {"email" => email, "password" => password, "phone" => new_phone}.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.save_new_password(params)
    YAML.load(User.post("reset_password", params.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.get_match_phone(params)
    YAML.load(Payment.post("buy_phone", params.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
    nil
  end
  
  def self.suspend_account(params)
	YAML.load(User.post("inactivate_account", params.merge({"key"=>@@KEYLOGINCAFE})).body)
  rescue StandardError => p
	nil
  end
end

app/views/members_am_cafe/customer_support_finish.html.erb
<div class="row" style="padding-top:15px;">
	<div id="main">
	<div id="content">
		<h2 class="form_title">送信されました。</span></h2>
		
		
		
	
	    <table cellpadding="0" cellspacing="0" border="0">
			<tbody>
				
			 	<tr><td class="comment_delete">11amcafeにご連絡いただき、ありがとうございます。<br>
                まもなくメールで返答させていただきますので、しばらくお待ちください。</td></tr>
                	
			</tbody>
		</table>
		
	</div>
	</div>
</div>

app/views/members_am_cafe/delete_account.html.erb
<div class="row" style="padding-top:15px;">
	<div id="main">
	<div id="content">
		<h2 class="delete_title">休会または退会しますか？</span></h2>
		
		
	
	    <table id="delete_table" cellpadding="0" cellspacing="0" border="0">
			<tbody>
				<%=form_tag delete_final_path, :method=>:post do%>
					<%=hidden_field_tag "email", @ses[:email]%>
			 		<tr><td class="instruction">休会を希望される方は、パスワードを入力後、下記ボタンをクリックしてください。</td></tr>
                	<tr><td><input class="inputtext_delete" name="password" type="password" placeholder="パスワード"></td></tr>
					<tr><td><input class="orange button" id="suspend_account_button" type="submit" value="休会する"></td></tr>
				<%end%>
				<%=form_tag suspend_final_path, :method=>:post do%>
					<%=hidden_field_tag "email", @ses[:email]%>
                	<tr><td class="instruction">退会を希望される方は、パスワードを入力後、下記ボタンをクリックしてください。</td></tr>
					<tr><td class="warning_delete">※一度削除したアカウントは再開することができませんので、ご注意ください。</td></tr>
                	<tr><td><input class="inputtext_delete" name="password" type="password" placeholder="パスワード"></td></tr>
					<tr><td><input class="orange button" id="delete_account_button" type="submit" value="退会する"></td></tr>
                <%end%>
			</tbody>
		</table>
		
	</div>
	</div>
</div>

app/views/members_am_cafe/edit_profile.html.erb
<div class="row" style="padding-top:15px;">
	<div id="main">
	<div id="content">
		<%if flash[:notice]%>
		<div class="alert alert-success" style="padding-top:15px">
		<a class="close" href="#" data-dismiss="alert">&times;</a>
		<%=flash[:notice]%>
		</div>
		<%end%>
		<%if flash[:error]%>
		<div class="alert alert-error" style="padding-top:15px">
			<a class="close" href="#" data-dismiss="alert">&times;</a>
		<%=flash[:error]%>
		</div>
		<%end%>
		<h2 class="title">プロフィールを変更しますか？</h2>
		
		
		<%=form_tag save_basic_info_path, :method=>:post do%>
		<%=hidden_field_tag "user[email]", @ses[:email]%>
	
	    <table id="edit_profile_table" cellpadding="0" cellspacing="0" border="0">
 		<tr><td colspan="2" class="xtd edit_title">基本情報の変更</td></tr>    
		<tr>
					<td class="xtd td_title"> メールアドレス</td>
					<td class="xtd td_input"><%=@ses[:email]%></td>
				</tr>
				<tr>
                	<td class="xtd td_title">名前（カタカナ）</td>
					<td class="xtd td_input"><%=text_field_tag "user[name]", @member ? @member["name"]: "", :class=>"inputtext_edit_profile"%></td>
				</tr>
				<tr><td class="xtd td_title">誕生日</td>
				<td class="xtd td_input">
					<%if @member && @member["birthdate"]%>
						<%=date_select :user, :birthdate, {:start_year =>  Time.zone.now.year - 40, :end_year => Time.zone.now.year - 18, :default => @member["birthdate"].to_date}, {:class=>"select"}%>
					<%else%>
						<%=date_select :user, :birthdate, {:start_year =>  Time.zone.now.year - 40, :end_year => Time.zone.now.year - 18}, {:class=>"select"}%>
					<%end%>
					
</td>
</tr>
             
             
								 <tr>
								<td class="xtd td_title">お住まいの地域</td>
										
			<td class="xtd td_input">					<select class="select" name="user[city]" id="user_city">
								<option value="0" >地域を選択:</option>
								<option value="tokyo" <%=(@member && @member["city"] && @member["city"].eql?("tokyo")) ? "selected" : ""%>><%=I18n.t(:tokyo)%></option>
						<option value="kanagawa" <%=(@member && @member["city"] && @member["city"].eql?("kanagawa")) ? "selected" : ""%>><%=I18n.t(:kanagawa)%></option>
						<option value="saitama" <%=(@member && @member["city"] && @member["city"].eql?("saitama")) ? "selected" : ""%>><%=I18n.t(:saitama)%></option>
						<option value="chiba" <%=(@member && @member["city"] && @member["city"].eql?("chiba")) ? "selected" : ""%>><%=I18n.t(:chiba)%></option>
						<option value="tochigi" <%=(@member && @member["city"] && @member["city"].eql?("tochigi")) ? "selected" : ""%>><%=I18n.t(:tochigi)%></option>
						<option value="ibaraki" <%=(@member && @member["city"] && @member["city"].eql?("ibaraki")) ? "selected" : ""%>><%=I18n.t(:ibaraki)%></option>
						<option value="gunma" <%=(@member && @member["city"] && @member["city"].eql?("gunma")) ? "selected" : ""%>><%=I18n.t(:gunma)%></option>
						<option value="aichi" <%=(@member && @member["city"] && @member["city"].eql?("aichi")) ? "selected" : ""%>><%=I18n.t(:aichi)%></option>
						<option value="gifu" <%=(@member && @member["city"] && @member["city"].eql?("gifu")) ? "selected" : ""%>><%=I18n.t(:gifu)%></option>
						<option value="shizuoka" <%=(@member && @member["city"] && @member["city"].eql?("shizuoka")) ? "selected" : ""%>><%=I18n.t(:shizuoka)%></option>
						<option value="mie" <%=(@member && @member["city"] && @member["city"].eql?("mie")) ? "selected" : ""%>><%=I18n.t(:mie)%></option>
						<option value="osaka" <%=(@member && @member["city"] && @member["city"].eql?("osaka")) ? "selected" : ""%>><%=I18n.t(:osaka)%></option>
						<option value="hyogo" <%=(@member && @member["city"] && @member["city"].eql?("hyogo")) ? "selected" : ""%>><%=I18n.t(:hyogo)%></option>
						<option value="kyoto" <%=(@member && @member["city"] && @member["city"].eql?("kyoto")) ? "selected" : ""%>><%=I18n.t(:kyoto)%></option>
						<option value="shiga" <%=(@member && @member["city"] && @member["city"].eql?("shiga")) ? "selected" : ""%>><%=I18n.t(:shiga)%></option>
						<option value="nara" <%=(@member && @member["city"] && @member["city"].eql?("nara")) ? "selected" : ""%>><%=I18n.t(:nara)%></option>
						<option value="wakayama" <%=(@member && @member["city"] && @member["city"].eql?("wakayama")) ? "selected" : ""%>><%=I18n.t(:wakayama)%></option>	
						</select>
	</td>
</tr>

								
			
                                <tr>
									<td class="xtd td_title">性別</td>
									<td class="xtd td_input">
                                 		<%=radio_button_tag "user[gender]", "male", @member["gender"].eql?("male")%><%=t(:male)%> 
										<%=radio_button_tag "user[gender]", "female", @member["gender"].eql?("female")%><%=t(:female)%>
		
									</td>
								</tr>
								<tr>
									<td class="xtd td_title">血液型</td>
									<td class="xtd td_input">
										<%=radio_button_tag "user[bloodType]", "A", @member && @member["bloodType"] && @member["bloodType"].eql?("A") ? true: false%>A型
										<%=radio_button_tag "user[bloodType]", "B", @member && @member["bloodType"] && @member["bloodType"].eql?("B") ? true: false%>B型
										<%=radio_button_tag "user[bloodType]", "AB", @member && @member["bloodType"] && @member["bloodType"].eql?("AB") ? true: false%>AB型
										<%=radio_button_tag "user[bloodType]", "0", @member && @member["bloodType"] && @member["bloodType"].eql?("0") ? true: false%>O型
									</td>
                                 </tr>
                                
								
								<tr>
									<td class="xtd td_title">相手の希望年齢</td>
									<td class="xtd td_input">
										<%=radio_button_tag "user[age_preference]", "older", @member["age_preference"].eql?("older")%><%=t(:older)%>
										 <%=radio_button_tag "user[age_preference]", "younger", @member["age_preference"].eql?("younger")%><%=t(:younger)%>
										 <%=radio_button_tag "user[age_preference]", "none", @member["age_preference"].eql?("none")%><%=t(:none)%>
					</td>
				</tr>
				<tr><td colspan="2" class="xtd td_button"><input class="orange button" id="profile_save_button" name="submit" type="submit" value="保存する"></td>
					<%end%>
					<%=form_tag save_new_phone_path, :method=>:post do%>
					<%=hidden_field_tag "user[email]", @ses[:email]%>				
				</tr>
                <tr><td colspan="2" class="xtd edit_title">携帯電話番号の変更</td></tr>
				<tr><td class="xtd td_title">携帯電話番号（ハイフンなし）</td>
					<td class="xtd td_input"><%if @member%>
					<%=text_field_tag "user[phone]", @member["phone"], :class=>"inputtext"%>
					<%else%>
					<%=text_field_tag "user[phone]", :class=>"inputtext"%>
					<%end%></td></tr>
                <tr><td class="xtd td_title">パスワード</td>
					<td class="xtd td_input"><%=password_field_tag "user[password]",nil, :class=>"inputtext"%></td></tr>
                <tr><td colspan="2" class="xtd td_button"><input class="orange button" id="profile_save_button" name="submit" type="submit" value="保存する"></td>
				</tr>
				<%end%>
				<%=form_tag save_new_password_path, :method=>:post do%>
				<%=hidden_field_tag "user[email]", @ses[:email]%>
                <tr><td colspan="2" class="xtd edit_title">パスワードの変更</td></tr>
                <tr><td class="xtd td_title">現在のパスワード</td>
					<td class="xtd td_input"><%=password_field_tag "user[password]", nil, :class=>"inputtext"%></td>
				</tr>
                <tr><td class="xtd td_title">新しいパスワード</td>
					<td class="xtd td_input"><%=password_field_tag "user[new_password]", nil, :class=>"inputtext"%></td>
                </tr>
                <tr><td class="xtd td_title">新しいパスワード（確認用）</td>
					<td class="xtd td_input"><%=password_field_tag "user[new_password2]", nil, :class=>"inputtext"%></td>
                </tr>
                <tr><td colspan="2" class="td">
                	<input class="orange button" id="profile_save_button" name="submit_button" type="submit" value="保存する">
                    </td>
				</tr>
				<%end%>	
				<tr><td colspan="2" class="delete_account"><%=link_to "アカウントを停止または削除する", delete_account_path%></td></tr>   	
	
			</tbody>
		</table>
		
	</div>
	</div>
</div>

app/views/members_am_cafe/index.html.erb
<%= button_to t(:edit_basic_data), edit_profile_path, :method=>:get%>
<%if !@user_active%>
<%= button_to t(:validate_account), validation_path, :method=>:get%>
<%end%>
<%= button_to t(:additional_profile_informatio), add_user_information_path, :method=>:get%>
<%= button_to t(:logout), logout_path, :method=>:get%>

app/views/members_am_cafe/validate_email_web.html.erb
<h2>E-Mail verified successfully!</h2>

<%=link_to "Go Back", members_path%>

app/views/members_am_cafe/validate_sms.html.erb
<h2>SMS verified successfully!</h2>

<%=link_to "Go Back", members_path%>

app/views/members_am_cafe/validation.html.erb
<div class="row" style="padding-top:15px;">
	<div id="main">
	<div id="content">
		<%if flash[:notice]%>
		<div class="alert alert-success">
		<a class="close" href="#" data-dismiss="alert">&times;</a>
		<%=flash[:notice]%>
		</div>
		<%end%>
		<%if flash[:error]%>
		<div class="alert alert-error">
			<a class="close" href="#" data-dismiss="alert">&times;</a>
		<%=flash[:error]%>
		</div>
		<%end%>
		<h2 class="title">携帯メールアドレス認証</span></h2>		
	
	    <table id="activation_table" cellpadding="0" cellspacing="0" border="0">
			<tbody>
<%= form_tag validate_email_web_path, :method => :get do%>
<%= hidden_field_tag "email", @ses[:email]%>	
				<tr><td class="instruction">携帯メールに送られてきた認証コードを入力してください。</td></tr>
               
				<tr><td><input class="inputtext_act" name="code" type="text" placeholder="認証コード"></td></tr>
                
				<tr><td class="td_recover_button">
                <input class="orange button" id="submit_code_button" type="submit" value="認証コードを送信する"></td></tr>

                <tr><td class="warning">au、DoCoMo、SoftBankの携帯メールアドレスを入力してください。<br>
                ドメイン指定受信を設定されている方は「11amcafe.com」を受信できるように設定してください。</td></tr>
<%end%>
<%=form_tag send_email_validation_path, :method => :get do%>
<%= hidden_field_tag "email", @ses[:email]%>
			 	<tr><td class="instruction">確認メールを再送信する場合、パスワードを入力して再送信ボタンをクリックしてください。</td></tr>
				<tr><td><%= password_field_tag "password","", :class=>"inputtext_act" %></td></tr>
				<tr><td class="td_recover_button">
                <input class="orange button" id="resend_email_button" type="submit" value="確認メールを再送信する"></td></tr>

<%end%>

			</tbody>
		</table>
		
	</div>
	</div>
</div>