config/routes.rb
ElevenAMcafe::Application.routes.draw do

match 'matches/new', :action =>'new', :controller => 'matches', :as=>'new', :via =>'POST'
match 'matches/show', :action =>'show', :controller =>'matches', :as=>'show', :via => 'GET'
match 'matches', :action => 'delete_match', :controller =>'matches', :as=>'delete_match', :via => 'DELETE'
match '11amcafe', :action => 'index', :controller =>'elevenAmCafe', :as => 'welcome', :via => 'GET'
match '11amcafe/customer_support', :action => 'customer_support', :controller =>'elevenAmCafe', :as => 'customer_support', :via => 'GET'
match '11amcafe/forget_password', :action => 'forget_password', :controller =>'elevenAmCafe', :as => 'forget_password', :via => 'GET'
match '11amcafe/send_forgotten_password', :action => 'send_forgotten_password', :controller =>'elevenAmCafe', :as => 'send_forgotten_password', :via => 'POST'
match '11amcafe/sweep_old_sessions', :action => 'sweep_old_sessions', :controller =>'elevenAmCafe', :via => 'GET'
match '11amcafe/get_picture/:name', :action => 'get_picture_ss', :controller => 'elevenAmCafe', :as => 'get_picture_ss', :via => 'GET'
match '11amcafe/add_picture', :action => 'add_picture_ss', :controller => 'elevenAmCafe', :as => 'add_picture_ss', :via => 'POST'
match '11amcafe/delete_picture', :action => 'delete_picture_ss', :controller => 'elevenAmCafe', :as => 'delete_picture_ss', :via => 'GET'
match '11amcafe/save_user_information', :action => 'save_user_information_ss', :controller => 'elevenAmCafe', :as => 'save_user_information_ss', :via => 'POST'

match '11amcafe/company', :action => 'company', :controller => 'help', :as => 'company', :via => 'GET'
match '11amcafe/privacy', :action => 'privacy', :controller => 'help', :as => 'privacy', :via => 'GET'
match '11amcafe/policy', :action => 'policy', :controller => 'help', :as => 'policy', :via => 'GET'
match '11amcafe/help', :action => 'help', :controller => 'help', :as => 'help', :via => 'GET'

match 'users', :action => 'index', :controller => 'usersAmCafe', :as => 'users', :via => 'GET'
match 'users', :action => 'create', :controller => 'usersAmCafe', :via => 'POST'
match 'users/new', :action => 'new', :controller => 'usersAmCafe', :as => 'new_user', :via => 'GET'
match 'users', :action => 'destroy', :controller => 'usersAmCafe', :as => 'delete', :via => 'DELETE'
match 'users/sign_in', :action => 'sign_in', :controller => 'usersAmCafe', :as => 'sign_in', :via => 'POST'
match 'users/second_step_new_user', :action => 'second_step_new_user', :controller => 'usersAmCafe', :as => 'second_step_new_user', :via => 'GET'

match 'members', :action => 'index', :controller => 'membersAmCafe', :as => 'members', :via => 'GET'
match 'members/add_picture', :action => 'add_picture', :controller => 'membersAmCafe', :as => 'add_picture', :via => 'POST'
match 'members/get_picture/:name', :action => 'get_picture', :controller => 'membersAmCafe', :as => 'get_picture', :via => 'GET'
match 'members/delete_picture', :action => 'delete_picture', :controller => 'membersAmCafe', :as => 'delete_picture', :via => 'GET'
match 'members/validation', :action => 'validation', :controller => 'membersAmCafe', :as => 'validation', :via => 'GET'
match 'members/validate_sms', :action => 'validate_sms', :controller => 'membersAmCafe', :as => 'validate_sms', :via => 'GET'
match 'members/validate_email', :action => 'validate_email', :controller => 'membersAmCafe', :as => 'validate_email', :via => 'GET'
match 'members/validate_email_web', :action => 'validate_email_web', :controller => 'membersAmCafe', :as => 'validate_email_web', :via => 'GET'
match 'members/edit_profile', :action => 'edit_profile', :controller => 'membersAmCafe', :as => 'edit_profile', :via => 'GET'
match 'members/add_user_information', :action => 'add_user_information', :controller => 'membersAmCafe', :as => 'add_user_information', :via => 'GET'
match 'members/save_basic_info', :action => 'save_basic_info', :controller => 'membersAmCafe', :as => 'save_basic_info', :via => 'POST'
match 'members/save_new_phone', :action => 'save_new_phone', :controller =>'membersAmCafe', :as => 'save_new_phone', :via => 'POST'
match 'members/save_new_password', :action => 'save_new_password', :controller =>'membersAmCafe', :as => 'save_new_password', :via => 'POST'
match 'members/save_user_information', :action => 'save_user_information', :controller => 'membersAmCafe', :as => 'save_user_information', :via => 'POST'
match 'members/send_sms_validation', :action => 'send_sms_validation', :controller => 'membersAmCafe', :as => 'send_sms_validation', :via => 'GET'
match 'members/send_email_validation', :action => 'send_email_validation', :controller => 'membersAmCafe', :as => 'send_email_validation', :via => 'GET'
match 'members/logout', :action => 'logout', :controller => 'membersAmCafe', :as => 'logout', :via => 'GET'
match 'members/save_password', :action => 'save_password', :controller =>'membersAmCafe', :as => 'save_password', :via => 'POST'
match 'members/new_password', :action => 'new_password', :controller =>'membersAmCafe', :as => 'new_password', :via => 'GET'
match 'members/show_matches', :action => 'show_matches', :controller =>'membersAmCafe', :as => 'show_matches', :via => 'GET'
match 'members/not_activated', :action => 'not_activated', :controller =>'membersAmCafe', :as => 'not_activated', :via => 'GET'
match 'members/get_picture_match/:name', :action => 'get_picture_match', :controller =>'membersAmCafe', :as => 'get_picture_match', :via => 'GET'
match 'members/choose_match', :action => 'choose_match', :controller => 'membersAmCafe', :as => 'choose_match', :via => 'GET'
match 'members/like_match', :action => 'like_match', :controller => 'membersAmCafe', :as => 'like_match', :via => 'POST'
match 'members/customer_support', :action => 'customer_support', :controller =>'membersAmCafe', :as => 'member_customer_support', :via => 'GET'
match 'members/customer_support_finish', :action => 'customer_support_finish', :controller =>'membersAmCafe', :as => 'customer_support_finish', :via => 'GET'
match 'members/get_match_phone', :action => 'get_match_phone', :controller => 'membersAmCafe', :as => 'get_match_phone', :via => 'POST'
match 'members/save_rating', :action => 'save_rating', :controller => 'membersAmCafe', :as => 'save_rating', :via => 'POST'
match 'members/company_l', :action => 'company_l', :controller => 'membersAmCafe', :as => 'company_l', :via => 'GET'
match 'members/privacy_l', :action => 'privacy_l', :controller => 'membersAmCafe', :as => 'privacy_l', :via => 'GET'
match 'members/policy_l', :action => 'policy_l', :controller => 'membersAmCafe', :as => 'policy_l', :via => 'GET'
match 'members/help_l', :action => 'help_l', :controller => 'membersAmCafe', :as => 'help_l', :via => 'GET'
match 'members/delete_account', :action => 'delete_account', :controller => 'membersAmCafe', :as => 'delete_account', :via => 'GET'
match 'members/delete_final', :action => 'delete_final', :controller => 'membersAmCafe', :as => 'delete_final', :via => 'POST'
match 'members/suspend_final', :action => 'suspend_final', :controller => 'membersAmCafe', :as => 'suspend_final', :via => 'POST'

match 'admin/admin_profile', :action => 'admin_profile', :controller => 'adminAmCafe', :as =>'admin_profile', :via => 'GET'
match 'admin/save_admin_new_password', :action => 'save_admin_new_password', :controller => 'adminAmCafe', :as => 'save_admin_new_password', :via => 'POST'
match 'admin/show_invalid_male_users', :action => 'show_invalid_male_users', :controller => 'adminAmCafe', :as => 'show_invalid_male_users', :via => 'GET'
match 'admin/show_invalid_female_users', :action => 'show_invalid_female_users', :controller => 'adminAmCafe', :as => 'show_invalid_female_users', :via => 'GET'
match 'admin/validate_user', :action => 'validate_user', :controller => 'adminAmCafe', :as => 'validate_user', :via => 'POST'
match 'admin/reject_user', :action => 'reject_user', :controller => 'adminAmCafe', :as => 'reject_user', :via => 'POST'
match 'admin/get_user_picture/:name', :action => 'get_user_picture', :controller => 'adminAmCafe', :as => 'get_user_picture', :via => 'GET'

end

app/controllers/admin_am_cafe_controller.rb
class AdminAmCafeController < ApplicationController
  layout "admin"
  before_filter :checkCredentials
  
  def checkCredentials
    #Session.sweep
    @ses = Session.find_by_session_id(cookies["authenticity_token"]) if cookies["authenticity_token"]
    if @ses.nil? || !UsersAmCafe.isAdmin?(@ses[:email])
      flash[:error] = I18n.t(:login_error)
      cookies.permanent["authenticity_token"]=nil
      reset_session
      redirect_to welcome_path
      return
    end
    @ses.save # update session to keep member logged in (automatically logged off after 7 days of inactivity)
    #session[:active] ||=  MembersAmCafe.is_active(@ses.email)
    #session[:has_match] ||= Match.has_match(@ses.email)
    #start_time = DateTime.now+2.hours
    #end_time = DateTime.new(Time.now.year, Time.now.month, Time.now.day, 11, 0, 0)
    #if start_time > end_time
    #  tomorrow = Time.now + 1.day
    #  end_time = DateTime.new(tomorrow.year, tomorrow.month, tomorrow.day, 11, 0, 0)
    #end
    #session[:end_time]=end_time
    #@time_to_rematch = ((end_time - start_time) * 24 * 60 * 60).to_i
  end
  
  def admin_profile
    @member = UsersAmCafe.getUser(@ses[:email])[:user]
  end
  
  def show_invalid_male_users
    if params && params["email"]
      next_user = params["email"]
    end
    users = UsersAmCafe.getAllToValidate
    @all_users=[]
    users.each do |user|
      #valid_status = MembersAmCafe.validation_status(user)
      @all_users << user if PicturesAmCafe.how_many_pictures?(user)>=2 && UsersAmCafe.has_advance_data?(user) && UsersAmCafe.is_male?(user) #&& !valid_status["email_validation_date"].nil?
      break if @all_users.count>=10
    end
    
    #next_user = UsersAmCafe.getNextToValidate
    next_user ||= @all_users[0] if @all_users && @all_users.size>0 && @all_users[0]
    
    if next_user && !next_user.eql?("")
      @user = UsersAmCafe.getUser(next_user)[:user]
    end
    @user_gender = "male"
    render :show_invalid_users
  end
  
  def show_invalid_female_users
    if params && params["email"]
      next_user = params["email"]
    end
    users = UsersAmCafe.getAllToValidate
    @all_users=[]
    users.each do |user|
      #valid_status = MembersAmCafe.validation_status(user)
      @all_users << user if PicturesAmCafe.how_many_pictures?(user)>=2 && UsersAmCafe.has_advance_data?(user) && !UsersAmCafe.is_male?(user) #&& !valid_status["email_validation_date"].nil?
      break if @all_users.count>=10
    end
    
    #next_user = UsersAmCafe.getNextToValidate
    next_user ||= @all_users[0] if @all_users && @all_users.size>0 && @all_users[0]
    
    if next_user && !next_user.eql?("")
      @user = UsersAmCafe.getUser(next_user)[:user]
    end
    @user_gender = "female"
    render :show_invalid_users
  end
  
  def validate_user
    UsersAmCafe.adminValidateUser(params["email"])
    if params["gender"] && params["gender"].eql?("male") 
      redirect_to show_invalid_male_users_path
      return
    else  
      redirect_to show_invalid_female_users_path
      return
    end
  end
  
  def reject_user
    UsersAmCafe.adminRejectUser(params["email"])
    if params["gender"] && params["gender"].eql?("male") 
      redirect_to show_invalid_male_users_path 
      return
    else  
      redirect_to show_invalid_female_users_path
      return
    end
  end
  
  def get_user_picture
    url = PicturesAmCafe.getPicture(params["email"],params["name"], params["type"])
    redirect_to url.to_s
  end
  
  def save_admin_new_password
    if params["user"].nil? || params["user"]["email"].nil? || params["user"]["password"].nil? || params["user"]["new_password"].nil? ||
      params["user"]["new_password2"].nil? || !params["user"]["new_password"].eql?(params["user"]["new_password2"])
      flash[:error] = I18n.t(:password_change_error)
    else
      if params["user"]["password"].eql?(params["user"]["new_password"])
        flash[:notice] = I18n.t(:password_change_correct)
      else
        auth_response = MembersAmCafe.save_new_password(params["user"])
        if auth_response.nil? || auth_response["message"].nil? || auth_response["message"].eql?("false") || !auth_response.instance_of?(Hash)
          flash[:error] = I18n.t(:password_change_error)
        else
          flash[:notice] = I18n.t(:password_change_correct)
        end
      end
    end
    redirect_to admin_profile_path
  end
  
end

app/views/admin_am_cafe/admin_profile.html.erb
<%if flash[:notice]%>
<div class="alert alert-success">
<a class="close" href="#" data-dismiss="alert">&times;</a>
<%=flash[:notice]%>
</div>
<%end%>
<%if flash[:error]%>
<div class="alert alert-error">
	<a class="close" href="#" data-dismiss="alert">&times;</a>
<%=flash[:error]%>
</div>
<%end%>
<table>
	<tr><td>
		<%=label_tag "email", t(:user_id)%></td><td>
	<%=text_field_tag "email", @ses[:email], :disabled => true%></td></tr>
</table>

<h3><%=t(:change_your_password)%></h3>
<br/>
<%=form_tag save_admin_new_password_path, :method=>:post do%>
<%=hidden_field_tag "user[email]", @ses[:email]%>
<table>
	<tr><td><%=label_tag "user_password", t(:old_password)%></td><td>
	<%=password_field_tag "user[password]"%></td></tr>
	<tr><td><%=label_tag "user_new_password", t(:new_password)%></td><td>
	<%=password_field_tag "user[new_password]"%></td></tr>
	<tr><td><%=label_tag "user_new_password2", t(:confirm_password)%></td><td>
	<%=password_field_tag "user[new_password2]"%></td></tr>
</table>
	<%=submit_tag t(:save)%>
<%end%>

app/views/admin_am_cafe/show_invalid_users.html.erb
<%if @user_gender && @user_gender.eql?("female")%>
<%url="/admin/show_invalid_female_users"%>
<%else%>
<%url="/admin/show_invalid_male_users"%>
<%end%>
<%=form_tag url, :method=>:get do%>
<%=select_tag "email", options_for_select(@all_users)%>
<%=submit_tag "GO"%>
<%end%>

<table>
	<tr><td class="category-title borderbottom"><%=t(:category_i_am)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "i_am")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_i_like)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "i_like")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_i_hate)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "i_hate")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_i_have)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "i_have")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_i_want)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "i_want")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_a_book)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "a_book")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_my_music)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "my_music")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_a_movie)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "a_movie")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_food)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "food")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_love_is)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "love_is")%></td></tr>
	<tr><td class="category-title borderbottom"><%=t(:category_my_job)%>: </td><td class="borderbottom category_value"><%=MemberHelper.category_in_a_list(@user, "my_job")%></td></tr>
</table>

<%if @user && @user["email"]%>
<table cellspacing="0" cellpadding="0">
<tr>
	<td><%=link_to image_tag("/admin/get_user_picture/1?type=t&email="+@user["email"], :size=>"210x280"),"/admin/get_user_picture/1?email="+@user["email"], :target => "blank" %></td>
	<td><%=link_to image_tag("/admin/get_user_picture/2?type=t&email="+@user["email"], :size=>"210x280"),"/admin/get_user_picture/2?email="+@user["email"], :target => "blank" %></td>
	<td><%=link_to image_tag("/admin/get_user_picture/3?type=t&email="+@user["email"], :size=>"210x280"),"/admin/get_user_picture/3?email="+@user["email"], :target => "blank" %></td>
	<td><%=link_to image_tag("/admin/get_user_picture/4?type=t&email="+@user["email"], :size=>"210x280"),"/admin/get_user_picture/4?email="+@user["email"], :target => "blank" %></td>
	<td><%=link_to image_tag("/admin/get_user_picture/5?type=t&email="+@user["email"], :size=>"210x280"),"/admin/get_user_picture/5?email="+@user["email"], :target => "blank" %></td>
</tr>
<%end%>
</table>
<table cellspacing="20px" cellpadding="20px">
	<tr><td><%=form_tag validate_user_path, :method=>:post do%>
		<%=hidden_field_tag "email", (@user && @user["email"])? @user["email"] : ""%>
		<%=hidden_field_tag "gender", (@user_gender) ? @user_gender : ""%>
		<%=submit_tag "Validate"%>
		<%end%></td><td><%=form_tag reject_user_path, :method=>:post do%>
		<%=hidden_field_tag "email", (@user && @user["email"])? @user["email"] : ""%>
		<%=hidden_field_tag "gender", (@user_gender) ? @user_gender : ""%>
		<%=submit_tag "Reject"%>
		<%end%></td>
	</tr>
</table>