config/routes.rb
ElevenAMcafe::Application.routes.draw do

match 'matches/new', :action =>'new', :controller => 'matches', :as=>'new', :via =>'POST'
match 'matches/show', :action =>'show', :controller =>'matches', :as=>'show', :via => 'GET'
match 'matches', :action => 'delete_match', :controller =>'matches', :as=>'delete_match', :via => 'DELETE'
match '11amcafe', :action => 'index', :controller =>'elevenAmCafe', :as => 'welcome', :via => 'GET'
match '11amcafe/customer_support', :action => 'customer_support', :controller =>'elevenAmCafe', :as => 'customer_support', :via => 'GET'
match '11amcafe/forget_password', :action => 'forget_password', :controller =>'elevenAmCafe', :as => 'forget_password', :via => 'GET'
match '11amcafe/send_forgotten_password', :action => 'send_forgotten_password', :controller =>'elevenAmCafe', :as => 'send_forgotten_password', :via => 'POST'
match '11amcafe/sweep_old_sessions', :action => 'sweep_old_sessions', :controller =>'elevenAmCafe', :via => 'GET'
match '11amcafe/get_picture/:name', :action => 'get_picture_ss', :controller => 'elevenAmCafe', :as => 'get_picture_ss', :via => 'GET'
match '11amcafe/add_picture', :action => 'add_picture_ss', :controller => 'elevenAmCafe', :as => 'add_picture_ss', :via => 'POST'
match '11amcafe/delete_picture', :action => 'delete_picture_ss', :controller => 'elevenAmCafe', :as => 'delete_picture_ss', :via => 'GET'
match '11amcafe/save_user_information', :action => 'save_user_information_ss', :controller => 'elevenAmCafe', :as => 'save_user_information_ss', :via => 'POST'

match '11amcafe/company', :action => 'company', :controller => 'help', :as => 'company', :via => 'GET'
match '11amcafe/privacy', :action => 'privacy', :controller => 'help', :as => 'privacy', :via => 'GET'
match '11amcafe/policy', :action => 'policy', :controller => 'help', :as => 'policy', :via => 'GET'
match '11amcafe/help', :action => 'help', :controller => 'help', :as => 'help', :via => 'GET'

match 'users', :action => 'index', :controller => 'usersAmCafe', :as => 'users', :via => 'GET'
match 'users', :action => 'create', :controller => 'usersAmCafe', :via => 'POST'
match 'users/new', :action => 'new', :controller => 'usersAmCafe', :as => 'new_user', :via => 'GET'
match 'users', :action => 'destroy', :controller => 'usersAmCafe', :as => 'delete', :via => 'DELETE'
match 'users/sign_in', :action => 'sign_in', :controller => 'usersAmCafe', :as => 'sign_in', :via => 'POST'
match 'users/second_step_new_user', :action => 'second_step_new_user', :controller => 'usersAmCafe', :as => 'second_step_new_user', :via => 'GET'

match 'members', :action => 'index', :controller => 'membersAmCafe', :as => 'members', :via => 'GET'
match 'members/add_picture', :action => 'add_picture', :controller => 'membersAmCafe', :as => 'add_picture', :via => 'POST'
match 'members/get_picture/:name', :action => 'get_picture', :controller => 'membersAmCafe', :as => 'get_picture', :via => 'GET'
match 'members/delete_picture', :action => 'delete_picture', :controller => 'membersAmCafe', :as => 'delete_picture', :via => 'GET'
match 'members/validation', :action => 'validation', :controller => 'membersAmCafe', :as => 'validation', :via => 'GET'
match 'members/validate_sms', :action => 'validate_sms', :controller => 'membersAmCafe', :as => 'validate_sms', :via => 'GET'
match 'members/validate_email', :action => 'validate_email', :controller => 'membersAmCafe', :as => 'validate_email', :via => 'GET'
match 'members/validate_email_web', :action => 'validate_email_web', :controller => 'membersAmCafe', :as => 'validate_email_web', :via => 'GET'
match 'members/edit_profile', :action => 'edit_profile', :controller => 'membersAmCafe', :as => 'edit_profile', :via => 'GET'
match 'members/add_user_information', :action => 'add_user_information', :controller => 'membersAmCafe', :as => 'add_user_information', :via => 'GET'
match 'members/save_basic_info', :action => 'save_basic_info', :controller => 'membersAmCafe', :as => 'save_basic_info', :via => 'POST'
match 'members/save_new_phone', :action => 'save_new_phone', :controller =>'membersAmCafe', :as => 'save_new_phone', :via => 'POST'
match 'members/save_new_password', :action => 'save_new_password', :controller =>'membersAmCafe', :as => 'save_new_password', :via => 'POST'
match 'members/save_user_information', :action => 'save_user_information', :controller => 'membersAmCafe', :as => 'save_user_information', :via => 'POST'
match 'members/send_sms_validation', :action => 'send_sms_validation', :controller => 'membersAmCafe', :as => 'send_sms_validation', :via => 'GET'
match 'members/send_email_validation', :action => 'send_email_validation', :controller => 'membersAmCafe', :as => 'send_email_validation', :via => 'GET'
match 'members/logout', :action => 'logout', :controller => 'membersAmCafe', :as => 'logout', :via => 'GET'
match 'members/save_password', :action => 'save_password', :controller =>'membersAmCafe', :as => 'save_password', :via => 'POST'
match 'members/new_password', :action => 'new_password', :controller =>'membersAmCafe', :as => 'new_password', :via => 'GET'
match 'members/show_matches', :action => 'show_matches', :controller =>'membersAmCafe', :as => 'show_matches', :via => 'GET'
match 'members/not_activated', :action => 'not_activated', :controller =>'membersAmCafe', :as => 'not_activated', :via => 'GET'
match 'members/get_picture_match/:name', :action => 'get_picture_match', :controller =>'membersAmCafe', :as => 'get_picture_match', :via => 'GET'
match 'members/choose_match', :action => 'choose_match', :controller => 'membersAmCafe', :as => 'choose_match', :via => 'GET'
match 'members/like_match', :action => 'like_match', :controller => 'membersAmCafe', :as => 'like_match', :via => 'POST'
match 'members/customer_support', :action => 'customer_support', :controller =>'membersAmCafe', :as => 'member_customer_support', :via => 'GET'
match 'members/customer_support_finish', :action => 'customer_support_finish', :controller =>'membersAmCafe', :as => 'customer_support_finish', :via => 'GET'
match 'members/get_match_phone', :action => 'get_match_phone', :controller => 'membersAmCafe', :as => 'get_match_phone', :via => 'POST'
match 'members/save_rating', :action => 'save_rating', :controller => 'membersAmCafe', :as => 'save_rating', :via => 'POST'
match 'members/company_l', :action => 'company_l', :controller => 'membersAmCafe', :as => 'company_l', :via => 'GET'
match 'members/privacy_l', :action => 'privacy_l', :controller => 'membersAmCafe', :as => 'privacy_l', :via => 'GET'
match 'members/policy_l', :action => 'policy_l', :controller => 'membersAmCafe', :as => 'policy_l', :via => 'GET'
match 'members/help_l', :action => 'help_l', :controller => 'membersAmCafe', :as => 'help_l', :via => 'GET'
match 'members/delete_account', :action => 'delete_account', :controller => 'membersAmCafe', :as => 'delete_account', :via => 'GET'
match 'members/delete_final', :action => 'delete_final', :controller => 'membersAmCafe', :as => 'delete_final', :via => 'POST'
match 'members/suspend_final', :action => 'suspend_final', :controller => 'membersAmCafe', :as => 'suspend_final', :via => 'POST'

match 'admin/admin_profile', :action => 'admin_profile', :controller => 'adminAmCafe', :as =>'admin_profile', :via => 'GET'
match 'admin/save_admin_new_password', :action => 'save_admin_new_password', :controller => 'adminAmCafe', :as => 'save_admin_new_password', :via => 'POST'
match 'admin/show_invalid_male_users', :action => 'show_invalid_male_users', :controller => 'adminAmCafe', :as => 'show_invalid_male_users', :via => 'GET'
match 'admin/show_invalid_female_users', :action => 'show_invalid_female_users', :controller => 'adminAmCafe', :as => 'show_invalid_female_users', :via => 'GET'
match 'admin/validate_user', :action => 'validate_user', :controller => 'adminAmCafe', :as => 'validate_user', :via => 'POST'
match 'admin/reject_user', :action => 'reject_user', :controller => 'adminAmCafe', :as => 'reject_user', :via => 'POST'
match 'admin/get_user_picture/:name', :action => 'get_user_picture', :controller => 'adminAmCafe', :as => 'get_user_picture', :via => 'GET'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElevenAMCafe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <style type="text/css">
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
		font: small 100% "Ryumin Light-KL";
		background-color: #40B8E5;
      }
	  .item {
		width:200px;
		height:200px;
	  }
   </style>

</head>
<body>
	<div class="navbar navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container-fluid row-fluid">
			
	          <div class="nav-collapse span10">
		  <%=link_to '11AMCafe', welcome_path, :class =>'brand'%>
	            <ul class="nav">
				  <li <%if params[:action].eql?("admin_profile")%>class="active"<%end%>><%=link_to t(:edit_basic_data), admin_profile_path%></li>
				  <li <%if params[:action].eql?("show_invalid_male_users")%>class="active"<%end%>><%=link_to t(:pending_male_validations), show_invalid_male_users_path%></li>
				 <li <%if params[:action].eql?("show_invalid_female_users")%>class="active"<%end%>><%=link_to t(:pending_female_validations), show_invalid_female_users_path%></li>
				  </ul>
	          </div><!--/.nav-collapse -->
			  <div class="span2 offset2">
				<ul class="nav">
  				  <li><%=link_to t(:logout), logout_path%></li>
				  <%if !params[:action].eql?("show_matches")%>
				  <li><a id="Time" href="#"></a></li>
				  <%end%>
				</ul>
			  </div>
	        </div>
	      </div>
	    </div>

	    <div class="container-fluid">
			<%= yield %>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>

		<script src="js/jquery.ah-placeholder.js"></script>
		<!-- ↓ah-placeholder.js の実行↓ -->
		<script>
		$(function() {
		  $('[placeholder]').ahPlaceholder({
		    placeholderColor : 'silver',
		    placeholderAttr : 'placeholder',
		    likeApple : true
		  });
		});
		</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
<title>11amCafe - 私たちの一期一会-</title>
	
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	<script>
	var TotalSeconds = <%= @time_to_rematch ? @time_to_rematch : 24*60*60%>;
	function countdown() {
		setTimeout('Decrement()',1);
	}
	function Decrement() {
		if (document.getElementById) {
			timex = document.getElementById("Time");
				var Seconds = TotalSeconds;

				    var Days = Math.floor(Seconds / 86400);
				    Seconds -= Days * 86400;

				    var Hours = Math.floor(Seconds / 3600);
				    Seconds -= Hours * (3600);

				    var Minutes = Math.floor(Seconds / 60);
				    Seconds -= Minutes * (60);
				if ((typeof (timex.textContent) != "undefined")){
	      			timex.textContent = LeadingZero(Hours) + ":" + LeadingZero(Minutes) + ":" + LeadingZero(Seconds);
			    }
			    else{
	      			timex.innerText = LeadingZero(Hours) + ":" + LeadingZero(Minutes) + ":" + LeadingZero(Seconds);
	   			}


			TotalSeconds--;
			if (TotalSeconds >0) {
				setTimeout('Decrement()',1000);
			}
			else {
				location.reload(true);
			}
		}
	}
	function LeadingZero(timex) {

	    return (timex < 10) ? "0" + timex : + timex;

	}
	</script>
	<script>
	<%if !params[:action].eql?("show_matches")%>
	countdown();
	<%end%>
	</script>
</head>
<body class="main_top">
 	<div>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
		   	  <div class="container">
		           <h3 style="margin:0;padding:0">
		           <a class="brand" style="margin:0;padding:0" href="/11amcafe">
		        	<img src="/assets/11amcafetoplogo.png" width="413" height="22">
		            </a>
		        	</h3>
					<!--<ul class="nav pull-right">
						<li><a href="/11amcafe"><i class="icon-home icon-white"></i>　トップ</a></li>
		            </ul>-->
				</div>  
			</div> 
		</div>

	    <div>
			<%= yield %>
		</div>

	</div>

	<div class="container" id="footer" style="margin-top:40px;">
	<div class="row" style="margin-left:110px;">



				<ul>
					<li><a href="/11amcafe/company">　運営会社</a></li>
	                <li><a href="/11amcafe/policy">　利用規約</a></li>
	                <li><a href="/11amcafe/privacy">　プライバシー</a></li>
	                <li><a href="/11amcafe/help">　ヘルプ</a></li>

	            </ul>
	            <span class="copyright">Copyright © 11amcafe All Rights Reserved</span>


	</div>  <!--row-->
	</div> <!--container-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script src="assets/bootstrap.min.js"></script>

	<script src="assets/jquery.ah-placeholder.js"></script>
	<!-- ↓ah-placeholder.js の実行↓ -->
	<script>
	$(function() {
	  $('[placeholder]').ahPlaceholder({
	    placeholderColor : 'silver',
	    placeholderAttr : 'placeholder',
	    likeApple : true
	  });
	});
	</script>
</html>

app/views/layouts/members.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
		<meta charset="UTF-8">
	<title>11amCafe - 私たちの一期一会-</title>

		  <%= stylesheet_link_tag    "application", :media => "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>

	  <script>
	var TotalSeconds = <%= @time_to_rematch ? @time_to_rematch : 24*60*60%>;
	function countdown() {
		setTimeout('Decrement()',1000);
	}
	function Decrement() {
		if (document.getElementById) {
			timex = document.getElementById("Time");
				var Seconds = TotalSeconds;

				    var Days = Math.floor(Seconds / 86400);
				    Seconds -= Days * 86400;

				    var Hours = Math.floor(Seconds / 3600);
				    Seconds -= Hours * (3600);

				    var Minutes = Math.floor(Seconds / 60);
				    Seconds -= Minutes * (60);
				if ((typeof (timex.textContent) != "undefined")){
	      			timex.textContent = LeadingZero(Hours) + ":" + LeadingZero(Minutes) + ":" + LeadingZero(Seconds);
			    }
			    else{
	      			timex.innerText = LeadingZero(Hours) + ":" + LeadingZero(Minutes) + ":" + LeadingZero(Seconds);
	   			}


			TotalSeconds--;
			if (TotalSeconds >0) {
				setTimeout('Decrement()',1000);
			}
			else {
				window.location.href='<%=welcome_path%>';
			}
		}
	}
	function LeadingZero(timex) {

	    return (timex < 10) ? "0" + timex : + timex;

	}
	</script>
	<script>
	<%if params[:action].eql?("show_matches") || params[:action].eql?("not_activated")%>
	countdown();
	<%end%>
	</script>
</head>
<body class="main_top">
<div>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
	   	  <div class="container">
	           <h3 style="margin:0;padding:0">
	           <a class="brand" style="margin:0;padding:0" href="/11amcafe">
	        	<img src="/assets/11amcafetoplogo.png" width="413" height="22">
	            </a>
	        	</h3>

				<ul class="nav pull-right">
					<li><a href="/11amcafe"><i class="icon-home icon-white"></i>　カフェトップ</a></li>
	                 <li><a href="/members/help_l.html"><i class="icon-question-sign icon-white"></i>　ヘルプ</a></li>
					<li class="dropdown" id="menu1"><a class="dropdown-toggle" data-toggle="dropdown" href="#menu1"><i class="icon-user icon-white"></i>　
	                プロフィール<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="/members/edit_profile"><i class="icon-user"></i>　基本情報</a></li>
						<li><a href="/members/add_user_information"> <i class="icon-camera"></i>　キーワード＆写真</a></li>
						<!--<li><a href="#"> <i class="icon-book"></i>　履歴</a></li>-->
						<%if !session[:active]%>
						<li class="divider"></li>
						<li><a href="/members/validation"> <i class="icon-warning-sign"></i>　アドレス認証</a></li>
						<li><a href="/members/customer_support"> <i class="icon-envelope"></i>　フィードバック</a></li>
						<%else%>
						<li class="divider"></li>
						<li><a href="/members/customer_support"> <i class="icon-envelope"></i>　フィードバック</a></li>
						<%end%>
						<li class="divider"></li>
						<li><a href="/members/logout"> <i class="icon-cog"></i>　ログアウト</a></li>
					</ul>
	                </li>
	            </ul>
			</div>  
		</div> 
	</div>
			
		

	    <div>
			<%= yield %>
		</div>
</div>



		<div class="container" id="footer" style="margin-top:40px;">
		<div class="row" style="margin-left:110px;">



					<ul>
						<li><a href="/members/company_l">　運営会社</a></li>
		                <li><a href="/members/policy_l">　利用規約</a></li>
		                <li><a href="/members/privacy_l">　プライバシー</a></li>
		                <li><a href="/members/help_l">　ヘルプ</a></li>

		            </ul>
		            <span class="copyright">Copyright © 11amcafe All Rights Reserved</span>


		</div>  <!--row-->
		</div> <!--container-->



	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script src="/assets/bootstrap.min.js"></script>

	<script src="/assets/jquery.ah-placeholder.js"></script>
	<script>
	$(function() {
	  $('[placeholder]').ahPlaceholder({
	    placeholderColor : 'silver',
	    placeholderAttr : 'placeholder',
	    likeApple : true
	  });
	});
	$(document).ready(function() {
	    $(".imgLiquid").imgLiquid();
	});
	</script>
	</body>
	</html>